export default function Footer() {
  return (
    <footer className="border-t border-zinc-200 dark:border-zinc-800 py-8 bg-zinc-50 dark:bg-zinc-950 mt-12 transition-colors duration-300">
      <div className="container mx-auto px-4 text-center text-zinc-500 dark:text-zinc-600 text-sm font-mono">
        <p>Generated by AutoRSS &bull; {new Date().getFullYear()}</p>
      </div>
    </footer>
  );
}
